added additional configs and a step that will fail under specific conditions.

diff --git a/.github/workflows/15-matrices.yaml b/.github/workflows/15-matrices.yaml
--- a/.github/workflows/15-matrices.yaml
+++ b/.github/workflows/15-matrices.yaml
@@ -7,16 +7,32 @@ jobs:
         name: ${{ matrix.os }}-${{ matrix.node-version }}
         runs-on: ${{ matrix.os }}
         strategy:
+            fail-fast: true # When any job fails all other jobs will be skipped. If set to false then jobs will continue if one fails. 
             matrix:
                 node-version: [20.x, 21.x, 22.x]
                 os:
                     - ubuntu-latest
                     #- macos-latest # commented out as this is expensive in a priv repo. 
                     - windows-latest
+                include: # this allows you to extende the configuraiton. 
+                   - os: ubunti-latest # this will adds a new job only for ubuntu and not windows. 
+                     node-version: 16.x
+                   - os: ubuntu-latest
+                     node-version: 21.x
+                     tag: experimental 
         steps:
             - name: Setup Node
               uses: actions/setup-node@v3
               with: 
                 node-version: ${{ matrix.node-version}}
+            - name: Fail if experimental
+              if: matrix.tag == 'experimental'
+              run: exit 1
             - name: Run Tests
-              run: echo Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node-version }}
+              run: | 
+                echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node-version }}"
+                sleep 5
+            - name: Upload test results
+              run: |
+                echo "Uploading test results"
+
